apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # This MUST be in the monitoring namespace
  namespace: monitoring
  
  # This is the name the helm chart will use
  name: loki-stack
  
  # These are the annotations for cert-manager and NGINX
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - lki.trivoconnect.com
    secretName: lki-tls-secret # This is the certificate to create
  rules:
  - host: lki.trivoconnect.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # This points to your running 'loki-stack' service
            name: loki-stack
            port:
              # This is the service port: 3100
              number: 3100