apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:neetesshhr/trivoconnect-argo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # --- THIS IS THE FIX ---
    # It must be a list of strings, not a list of objects.
    syncOptions:
    - "CreateNamespace=true"