apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:neetesshhr/trivoconnect-argo.git
    targetRevision: HEAD
    path: manifests
    
  # --- THIS IS THE FIX ---
  # The "root" app's job is to create other Applications.
  # All Application resources MUST be created in the "argocd" namespace.
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  # --- END OF FIX ---
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - "CreateNamespace=true"